### ISSUE TITLE
Enable appveyor

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/TextParse.jl#103]
@shashi can you enable appveyor?

@ViralBShah do you guys have a JuliaComputing appveyor account that corresponds to the github org here? I see a lot of personal appveyor accounts running on JuliaComputing repos, which seems not ideal. Wouldn't it make more sense to create a juliacomputing account on appveyor and use that? That is what I did for the whole queryverse org (see e.g. https://github.com/queryverse/Query.jl and https://ci.appveyor.com/project/queryverse/query-jl/branch/master).

**Comment by ViralBShah** [comment]
The general thought is that we want to move the JuliaDB set of packages to a separate org. So perhaps we can set it up right when we do that.

**Comment by davidanthoff** [comment]
Maybe @shashi could then enable a personal account until that happens? We have a lot of PRs pending here, and it would be good if they get properly tested.
