### ISSUE TITLE
Importing data with JuliaDB errors

### ISSUE THREAD

**Issue by jmbyars** [JuliaComputing/TextParse.jl#132]
I am trying to load several CSV files using JuliaDB. However, I am getting some errors loading the data with column fields with repect to TextParse. I even specified the column types using colparses, but it keeps getting rejected. Any thoughts on this bug?

![image](https://user-images.githubusercontent.com/9964645/55000115-2f68ad00-4fa8-11e9-9717-b76aa63a5e79.png)

**Comment by joshday** [comment]
I don't think it's a bug.  Try `colparsers = fill(String, 131)`.

**Comment by jmbyars** [comment]
That work. For some reason, fill("String", 131) was causing the problem. My experiences are in R so I am  used to putting quotes around column types.

**Comment by jmbyars** [comment]
Although when opening another dataset I get another error about inferring column types.

![image](https://user-images.githubusercontent.com/9964645/55005312-21b82500-4fb2-11e9-9c28-7a8e47a6a986.png)

**Comment by davidanthoff** [comment]
you need to pass the delim as a character, not a string, so as `'\t'` (use single quotes).

**Comment by davidanthoff** [comment]
I think we can close this, right?
