### ISSUE TITLE
any interest in not-currently-parsable CSVs?

### ISSUE THREAD

**Issue by tcovert** [JuliaComputing/TextParse.jl#19]
I have an example file which reads fine in `readtable()` from `DataFrames` but will not read using `TextParse` (or `CSV.read()`, for that matter): https://www.dropbox.com/s/hrutgyidhojujv9/WellIndex_20160811.csv?dl=0

Since I am able to get this data into Julia using `DataFrames` I am personally in good shape, but if the maintainers of this package are interested in non-parsable examples which should theoretically be parsable, this is one.

Thanks in advance if you are able fix `TextParse` to read this.

**Comment by shashi** [comment]
Thanks for the report! I'll take a look at this in a while.

**Comment by tcovert** [comment]
For what its worth, the (current) error I am seeing trying to use `csvread` in this file arises in a String column with a string that is double quoted, e.g.:

33043000030000,24,MAGNOLIA PETROLEUM CO.,NORTH DAKOTA STATE A     1,NORTH DAKOTA STATE A,1,MAGNOLIA PETROLEUM CO.,"NORTH DAKOTA STATE ""A"" #1",10/21/1950,5609,KIDDER,141 N,73 W,36,SENE,1980 FNL  810 FEL,WILDCAT,,,,VERTICAL,46.990158000000001,-99.864013,OG,DRY,,12/24/1950

after calling `csvread(file, type_detect_rows=100)`, I get this error:
```
ERROR: Couldn't split line, error at char 5675:
...E A,1,MAGNOLIA PETROLEUM CO.,"NORTH DAKOTA STATE ""A"" #1",10/21/1950,5609,KIDDER,141 N,73 W,36,SENE,...
____________________________________________________^
```

any idea how I might get around this error, aside from pre-processing out double quotation marks?

**Comment by shashi** [comment]
Ah okay!! So you need the `escapechar='"'` option to csvread. Escape char is '\' by default, and there's no mechanism to detect it.

**Comment by tcovert** [comment]
Oddly enough, I now get stuck at an earlier line than I was without specifying an escape character:
```
julia> wi = csvread("WellIndex_20160811.csv", escapechar = '"');
ERROR: Parse error at line 14 at char 85:
....",NELS KAMP     1,NELS KAMP,1,CALIFORNIA OIL CO.,NELS KAMP #1,10/01/1937,10281,WILLIAMS,154 N,96 W,3...
____________________________________________________^
CSV column 9 is expected to be: TextParse.Field{Nullable{Date},TextParse.NAToken{Nullable{Date},TextParse.DateTimeToken{Date,DateFormat{Symbol("mm/dd/yyyy"),Tuple{Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'y'}}}}}}(TextParse.DateTimeToken{Date,DateFormat{Symbol("mm/dd/yyyy"),Tuple{Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'y'}}}}(dateformat"mm/dd/yyyy")?, true, true, false, false, Nullable{Char}(','))
```
I'm not sure what this error is telling me.  Knowing that there are 27 columns in the file, I tried the `colparsers=fill(String, 27)` option as well, to avoid type detection, but I guess that doesn't work either:

```
julia> wi = csvread("WellIndex_20160811.csv", escapechar = '"', colparsers = fill(String, 27));
Could not determine which type to promote column to.
ERROR: Parse error at line 15 at char 220:
...,VERTICAL,48.195549,-103.008124,OG,DRY,,07/15/1986...
____________________________________________________^
CSV column 1 is expected to be: TextParse.Field{String,TextParse.StringToken{String}}(<string>, true, true, false, false, Nullable{Char}(','))
```

any hints on how I might fix this?

**Comment by shashi** [comment]
Can you upload the first 20 lines of the file?

**Comment by tcovert** [comment]
heres the first 30 or so: https://www.dropbox.com/s/hvjivsne8kkvg13/tp_example.csv?dl=0

**Comment by shashi** [comment]
```
csvread("tp_example.csv", type_detect_rows=20, colparsers=fill(Quoted(StrRange), 27), escapechar='"')
```
worked for me... It seems to be having trouble figuring out column 3 is quoted in some places... On line 14 there's a comma inside the quote which seems to be getting split at... I'll push a fix soon.

**Comment by davidanthoff** [comment]
Bump, I met Tom this week and he mentioned that these files still don't load, right?

**Comment by tcovert** [comment]
not yet but it seems like @shashi has a fix in the works?

**Comment by davidanthoff** [comment]
@shashi One more question re this: would the fix you are working on require one to specify the ``colparsers`` in the way you show above, or would things just start to work with a simple ``csvread(filename)``? I think the latter would be really great, i.e. if this would just work by default.

**Comment by tcovert** [comment]
@shashi any update on this?  If not, where should I start looking in the source to try to fix myself?

**Comment by davidanthoff** [comment]
Yeah, I also took a very brief look at the source because I thought I might take a stab but couldn't really find the starting point :)

**Comment by shashi** [comment]
A simple but robust solution was to treat string fields as possibly quoted by default. Now I can read the file with just `eschapechar='"'` as the only option.

**Comment by davidanthoff** [comment]
Yeah, that is great! Probably warrants a tagged release, right?

@tcovert Did you have more cases that didn't work so far? I'd really like to make sure we can read all files that worked with the old DataFrames.jl code before it gets removed!

**Comment by tcovert** [comment]
@davidanthoff been going through my various test cases, haven't found any yet!

**Comment by davidanthoff** [comment]
Cool!
