### ISSUE TITLE
handle byte order mark ('\ufeff`) character in the beginning of files

### ISSUE THREAD

**Issue by shashi** [JuliaComputing/TextParse.jl#49]
[Some info here.](https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string)

**Comment by quinnj** [comment]
For reference on how CSV.jl handles this: https://github.com/JuliaData/CSV.jl/blob/011a7f7d098d94266be2f50956a35d28db7075f4/src/Source.jl#L78

**Comment by shashi** [comment]
That's helpful. Thanks!

**Comment by davidanthoff** [comment]
This is implemented, correct? I'm closing for now.
