### ISSUE TITLE
Major perf regression on julia 1.0

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/TextParse.jl#73]
@quinnj found this, and all the details are described over at https://github.com/queryverse/CSVFiles.jl/issues/30.

@shashi is there a chance that you could take a look at that?

**Comment by davidanthoff** [comment]
@shashi any chance you might be able to look at this soon? Or some estimate when you might be able to take a look?

**Comment by davidanthoff** [comment]
I'm looking into this now and spending some time on that. If someone else has started, please let me know so that we don't duplicate efforts.

**Comment by shashi** [comment]
Sorry I haven't had time to look at this. I think this is not higher up on my list than WebIO bugs and porting JuliaDB at the moment. Your help is much appreciated!
