### ISSUE TITLE
Reading strings with escaped stuff seems incorrect

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/TextParse.jl#85]
For example here:
````julia
 s = "Foo \\\"bar"

tryparsenext(Quoted(String, quotechar='"', escapechar='\\'), s)
````
I would expect that to return a string with content:
````
Foo "bar
````
Instead I get
````
Foo \"bar
````

In general I'm confused how the strategy of essentially just returning a position and a length that indexes into the source string a la [this](https://github.com/JuliaComputing/TextParse.jl/blob/1646a4bf0945e9496c858eae455a14b9d82a44e6/src/field.jl#L359) can ever work properly in this situation. After all, if you read a string with an escape character, the parsed string should actually *not* include that escape character, so don't you necessarily need a different memory buffer for that?

@shashi am I missing something in my analysis?

**Comment by shashi** [comment]
> don't you necessarily need a different memory buffer for that?

Yes and that's why I avoided having this :p

**Comment by davidanthoff** [comment]
Alright, I might have a go at a fix. I think at the end of the day correctness is more important than speed. I'll try to do this in a way that the overhead doesn't kick in if there isn't an escape character.

**Comment by KristofferC** [comment]
See https://github.com/JuliaIO/JSON.jl/blob/741cbd5bbcc52d2310abb7ec0202f0993e457d18/src/specialized.jl#L25-L121
